source "https://rubygems.org"

ruby "2.4.3"

gem "bourbon", "~> 5.1"
gem "builder", "~> 3.2"
gem "middleman", "~> 4.2"
gem "middleman-aria_current", "~> 0.1"
gem "middleman-autoprefixer", "~> 2.9"
gem "middleman-livereload", "~> 3.4"
gem "middleman-minify-html", "~> 3.4"
gem "middleman-sprockets", "~> 4.1"
gem "middleman-syntax", "~> 3.0"
gem "neat", "~> 3.0"
gem "rails-assets-normalize-css", source: "https://rails-assets.org"
gem "rake", "~> 12.3"
gem "redcarpet", "~> 3.4"
gem "sassc"
