source "https://rubygems.org"

ruby "2.4.1"

gem "bourbon", "~> 5.0"
gem "builder", "~> 3.2"
gem "middleman", "~> 4.2"
gem "middleman-aria_current", "~> 0.1"
gem "middleman-autoprefixer", "~> 2.8"
gem "middleman-livereload", "~> 3.4"
gem "middleman-minify-html", "~> 3.4"
gem "middleman-sprockets", "~> 4.1"
gem "middleman-syntax", "~> 3.0"
gem "neat", "~> 2.1"
gem "rails-assets-normalize-css", source: "https://rails-assets.org"
gem "rails-assets-svg4everybody", source: "https://rails-assets.org"
gem "rake", "~> 12.0"
gem "redcarpet", "~> 3.4"
gem "sass", "~> 3.4"
gem "slim", "~> 3.0"
