source "https://rubygems.org"

ruby "2.5.3"

gem "bourbon"
gem "builder"
gem "middleman"
gem "middleman-aria_current"
gem "middleman-autoprefixer"
gem "middleman-minify-html"
gem "middleman-sprockets"
gem "middleman-syntax"
gem "neat"
gem "rails-assets-normalize-css", source: "https://rails-assets.org"
gem "rake"
gem "redcarpet"
gem "sassc"
