version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.3-node

    steps:
      - checkout

      - restore_cache:
          key: bourbon-io-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Install Percy CLI
          command: gem install percy-cli

      - save_cache:
          key: bourbon-io-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup the environment
          command: cp .env.sample .env

      - run:
          name: Build Middleman site
          command: bundle exec middleman build --verbose

      - run:
          name: Run Percy
          command: percy snapshot build/
